---
- name: Upload all files to the remote server
  become: true
  gather_facts: no
  hosts: all

  tasks:
    - name: Create remote directory if it does not exist
      ansible.builtin.file:
        path: "{{remote_workspace}}"
        state: directory
        mode: '0750'
        follow: false
        group: "{{remote_owner_group}}"
        owner: "{{remote_owner_user}}"
      no_log: True

    - name: Copy new application files to deployment path
      ansible.posix.synchronize:
        src: "{{local_workspace}}/"
        dest: "{{remote_workspace}}/"
        delete: yes
        recursive: yes
        perms: yes
        owner: no
        group: no
        rsync_opts:
          - "--exclude-from={{local_workspace}}/.ansible/files/rsync.ignore"
      no_log: True