---
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  release:
    name: Build & release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build  assets for production
        run: yarn build

      - name: Update files and directory permissions
        run: |
          sudo find ./assets -type d -exec chmod 0750 {} +
          sudo find ./assets  -type f -exec chmod 0644 {} +
          sudo find -type f -maxdepth 1 -exec chmod 0644 {} +


      #  Execute ansible playbooks
      - name: Create ansible temp env config directory
        run: sudo mkdir -p /home/ansible-temp

      - name: Run ansible deployment playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{github.workspace}}/.ansible/playbooks/deploy.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          requirements: ${{github.workspace}}/.ansible/files/requirements.yml
          directory: /home/ansible-temp
          inventory: |
            [all]
            ${{secrets.MAIN_SERVER}}
          options: |
            -u  ${{secrets.SSH_USER}}
            -e  "remote_workspace=${{secrets.REMOTE_WORKSPACE}}"
            -e  "local_workspace=${{github.workspace}}"
            -e  "remote_owner_group=${{secrets.REMOTE_OWNER_GROUP}}"
            -e  "remote_owner_user=${{secrets.REMOTE_OWNER_USER}}"